export const competitionsSeed = [
  {
    slug: "hul-lime-2026",
    title: "HUL L.I.M.E. Season XVII",
    organizer: "Hindustan Unilever Limited",
    description:
      "India's flagship B-school case competition across Leadership, Innovation, Marketing & Entrepreneurship. Campus rounds lead to zonal semi-finals and a national finale.",
    domain: "Marketing",
    format: "Campus Round → Zonal Semi-Finals → National Finale",
    registrationDeadline: new Date("2026-07-15"),
    preliminaryDate: new Date("2026-08-20"),
    eventDate: new Date("2026-10-18"),
    location: "Mumbai (Finale)",
    mode: "HYBRID",
    teamSizeMin: 2,
    teamSizeMax: 3,
    prizePool: "₹10 Lakhs + Pre-placement interviews",
    registrationUrl:
      "https://unstop.com/competitions/crp-hul-lime-season-17-hindustan-unilever-limited-hul-1531679",
    eligibility: "Full-time MBA/PGDM students from AICTE-approved B-schools",
    status: "REGISTRATION_OPEN",
    isFeatured: true,
    tags: ["corporate", "marketing", "flagship", "pre-placement"],
    hostCollege: null,
  },
  {
    slug: "flipkart-wired-2026",
    title: "Flipkart Wired",
    organizer: "Flipkart",
    description:
      "E-commerce and supply chain case competition on retail, logistics, and customer experience challenges drawn from Flipkart's operating context.",
    domain: "Operations",
    format: "Online Qualifier → Virtual Semi-Finals → On-campus Finale",
    registrationDeadline: new Date("2026-07-25"),
    preliminaryDate: new Date("2026-08-28"),
    eventDate: new Date("2026-09-20"),
    location: "Bangalore (Finale)",
    mode: "HYBRID",
    teamSizeMin: 2,
    teamSizeMax: 4,
    prizePool: "₹8 Lakhs + PPI opportunities",
    registrationUrl: "https://unstop.com/festival/flipkart-wired-80-flipkart-258277",
    eligibility: "MBA students from leading Indian B-schools",
    status: "REGISTRATION_OPEN",
    isFeatured: true,
    tags: ["e-commerce", "operations", "corporate"],
    hostCollege: null,
  },
  {
    slug: "amazon-ace-2026",
    title: "Amazon ACE Challenge",
    organizer: "Amazon India",
    description:
      "Amazon Customer Excellence (ACE) challenge — teams tackle real customer-obsession scenarios across retail and operations.",
    domain: "Strategy",
    format: "Online Case → Virtual Finals",
    registrationDeadline: new Date("2026-08-01"),
    preliminaryDate: new Date("2026-09-05"),
    eventDate: new Date("2026-09-27"),
    location: "Online",
    mode: "ONLINE",
    teamSizeMin: 2,
    teamSizeMax: 3,
    prizePool: "₹5 Lakhs + Amazon internships",
    registrationUrl:
      "https://unstop.com/competitions/crp-amazon-customer-excellence-ace-challenge-2025-amazon-1505288",
    eligibility: "1st and 2nd year MBA students",
    status: "REGISTRATION_OPEN",
    isFeatured: true,
    tags: ["corporate", "strategy", "technology"],
    hostCollege: null,
  },
  {
    slug: "mahindra-war-room-2026",
    title: "Mahindra War Room Season 12",
    organizer: "Mahindra Group",
    description:
      "Multi-domain case competition across automotive, farm equipment, IT, and financial services with CXO jury panels.",
    domain: "Strategy",
    format: "Campus → Regional → National Grand Finale",
    registrationDeadline: new Date("2026-08-10"),
    preliminaryDate: new Date("2026-09-12"),
    eventDate: new Date("2026-11-08"),
    location: "Mumbai",
    mode: "HYBRID",
    teamSizeMin: 3,
    teamSizeMax: 4,
    prizePool: "₹12 Lakhs + Mahindra Group PPIs",
    registrationUrl: "https://unstop.com/competitions/mahindra-war-room-mahindra-11374",
    eligibility: "MBA/PGDM students, all years",
    status: "UPCOMING",
    isFeatured: true,
    tags: ["corporate", "strategy", "flagship"],
    hostCollege: null,
  },
  {
    slug: "tata-crucible-2026",
    title: "Tata Crucible Campus Quiz",
    organizer: "Tata Group",
    description:
      "Tata Group's national business quiz and case-style campus challenge testing business acumen, strategy, and Tata group knowledge.",
    domain: "Strategy",
    format: "Campus Round → Regional → National Finals",
    registrationDeadline: new Date("2026-08-20"),
    preliminaryDate: new Date("2026-09-25"),
    eventDate: new Date("2026-10-25"),
    location: "Mumbai",
    mode: "HYBRID",
    teamSizeMin: 2,
    teamSizeMax: 2,
    prizePool: "₹7 Lakhs + Tata group exposure",
    registrationUrl:
      "https://unstop.com/competitions/tata-crucible-campus-quiz-tata-6335",
    eligibility: "MBA students from recognized Indian B-schools",
    status: "UPCOMING",
    isFeatured: false,
    tags: ["corporate", "quiz", "strategy"],
    hostCollege: null,
  },
  {
    slug: "asian-pact-2026",
    title: "Asian Pact",
    organizer: "Asian Paints",
    description:
      "Long-running marketing case competition focused on decorative paints, home décor, and brand challenges in the Indian market.",
    domain: "Marketing",
    format: "Campus Round → Zonal → National Finale",
    registrationDeadline: new Date("2026-08-05"),
    preliminaryDate: new Date("2026-09-08"),
    eventDate: new Date("2026-10-04"),
    location: "Mumbai",
    mode: "HYBRID",
    teamSizeMin: 2,
    teamSizeMax: 3,
    prizePool: "₹6 Lakhs",
    registrationUrl:
      "https://unstop.com/competitions/asian-pact-12-asian-paints-limited-11796",
    eligibility: "MBA/PGDM students nationwide",
    status: "REGISTRATION_OPEN",
    isFeatured: false,
    tags: ["marketing", "FMCG", "heritage"],
    hostCollege: null,
  },
  {
    slug: "itc-interrobang-2026",
    title: "ITC Interrobang",
    organizer: "ITC Limited",
    description:
      "Multi-round competition spanning FMCG, hotels, agri-business, and paperboards across ITC's diversified portfolio.",
    domain: "Strategy",
    format: "Online + Campus → National Finals",
    registrationDeadline: new Date("2026-08-15"),
    preliminaryDate: new Date("2026-09-18"),
    eventDate: new Date("2026-10-11"),
    location: "Kolkata",
    mode: "HYBRID",
    teamSizeMin: 2,
    teamSizeMax: 4,
    prizePool: "₹5 Lakhs + ITC PPIs",
    registrationUrl:
      "https://unstop.com/competitions/itc-interrobang-itc-limited-474",
    eligibility: "MBA students from premier B-schools",
    status: "UPCOMING",
    isFeatured: false,
    tags: ["corporate", "FMCG", "diversified"],
    hostCollege: null,
  },
  {
    slug: "mondelez-canvas-2026",
    title: "Mondelez Canvas",
    organizer: "Mondelez International",
    description:
      "Brand management and innovation challenge for confectionery and snacking brands including Cadbury and Oreo.",
    domain: "Marketing",
    format: "Virtual Case → On-campus Finale",
    registrationDeadline: new Date("2026-09-01"),
    preliminaryDate: new Date("2026-09-22"),
    eventDate: new Date("2026-10-17"),
    location: "Mumbai",
    mode: "HYBRID",
    teamSizeMin: 2,
    teamSizeMax: 3,
    prizePool: "₹3.5 Lakhs",
    registrationUrl:
      "https://unstop.com/competitions/mondelez-canvas-mondelez-international-1092",
    eligibility: "MBA students, marketing focus preferred",
    status: "UPCOMING",
    isFeatured: false,
    tags: ["FMCG", "branding", "innovation"],
    hostCollege: null,
  },
  {
    slug: "deloitte-ace-of-case-2026",
    title: "Deloitte Ace of Case",
    organizer: "Deloitte India",
    description:
      "Consulting case competition simulating client engagements with emphasis on structured problem-solving and executive presentation.",
    domain: "Strategy",
    format: "Campus → Regional → National",
    registrationDeadline: new Date("2026-09-05"),
    preliminaryDate: new Date("2026-10-03"),
    eventDate: new Date("2026-11-01"),
    location: "Hyderabad",
    mode: "HYBRID",
    teamSizeMin: 3,
    teamSizeMax: 4,
    prizePool: "₹4 Lakhs + Deloitte consulting PPIs",
    registrationUrl:
      "https://unstop.com/competitions/deloitte-ace-of-case-deloitte-347",
    eligibility: "MBA students interested in consulting",
    status: "UPCOMING",
    isFeatured: false,
    tags: ["consulting", "strategy", "corporate"],
    hostCollege: null,
  },
  {
    slug: "zs-case-challenge-2026",
    title: "ZS Associates Campus Challenge",
    organizer: "ZS Associates",
    description:
      "Healthcare and pharma consulting case competition solving data-driven problems for life sciences clients.",
    domain: "Analytics",
    format: "Online Case → Virtual Finals",
    registrationDeadline: new Date("2026-07-20"),
    preliminaryDate: new Date("2026-08-15"),
    eventDate: new Date("2026-09-06"),
    location: "Online",
    mode: "ONLINE",
    teamSizeMin: 2,
    teamSizeMax: 3,
    prizePool: "₹3 Lakhs + ZS internship offers",
    registrationUrl:
      "https://unstop.com/competitions/zs-associates-campus-challenge-zs-associates-1117",
    eligibility: "MBA students with analytics or pharma interest",
    status: "REGISTRATION_OPEN",
    isFeatured: false,
    tags: ["consulting", "healthcare", "analytics"],
    hostCollege: null,
  },
  {
    slug: "vista-iimb-2026",
    title: "Vista — Case Competition Track",
    organizer: "IIM Bangalore",
    description:
      "National case competition track at Vista, IIM Bangalore's annual business festival.",
    domain: "Strategy",
    format: "Online Prelims → On-campus Finals at IIMB",
    registrationDeadline: new Date("2026-08-30"),
    preliminaryDate: new Date("2026-09-26"),
    eventDate: new Date("2026-10-10"),
    location: "Bangalore",
    mode: "HYBRID",
    teamSizeMin: 2,
    teamSizeMax: 4,
    prizePool: "₹2 Lakhs",
    registrationUrl: "https://www.iimb-vista.com/",
    eligibility: "All B-school students in India",
    status: "UPCOMING",
    isFeatured: false,
    tags: ["B-school-fest", "national", "strategy"],
    hostCollege: "IIM Bangalore",
  },
  {
    slug: "confluence-iima-2026",
    title: "Confluence Case Masters",
    organizer: "IIM Ahmedabad",
    description:
      "Case competition at Confluence, IIMA's annual management symposium, judged by faculty and industry leaders.",
    domain: "Strategy",
    format: "On-campus at IIMA",
    registrationDeadline: new Date("2026-09-10"),
    eventDate: new Date("2026-10-17"),
    location: "Ahmedabad",
    mode: "OFFLINE",
    teamSizeMin: 2,
    teamSizeMax: 3,
    prizePool: "₹1.5 Lakhs",
    registrationUrl: "https://www.iimaconfluence.com/",
    eligibility: "Registered B-school teams",
    status: "UPCOMING",
    isFeatured: false,
    tags: ["B-school-fest", "strategy"],
    hostCollege: "IIM Ahmedabad",
  },
  {
    slug: "fms-fiesta-conquest-2026",
    title: "FMS Fiesta — Conquest Case Competition",
    organizer: "FMS Delhi (University of Delhi)",
    description:
      "Flagship case competition at FMS Fiesta, the annual business fest of Faculty of Management Studies, Delhi.",
    domain: "Strategy",
    format: "Online Prelims → FMS Delhi Finale",
    registrationDeadline: new Date("2026-07-10"),
    preliminaryDate: new Date("2026-08-01"),
    eventDate: new Date("2026-08-22"),
    location: "New Delhi",
    mode: "HYBRID",
    teamSizeMin: 2,
    teamSizeMax: 4,
    prizePool: "₹1 Lakh",
    registrationUrl:
      "https://unstop.com/competitions/conquest-2026-fiesta-2026-fms-du-new-delhi-1634397",
    eligibility: "MBA students from Indian B-schools",
    status: "REGISTRATION_OPEN",
    isFeatured: true,
    tags: ["Delhi-NCR", "B-school-fest", "pilot"],
    hostCollege: "FMS Delhi",
  },
  {
    slug: "mdi-imperium-2026",
    title: "MDI Imperium — National Case Competition",
    organizer: "MDI Gurgaon",
    description:
      "National case competition at Imperium, MDI Gurgaon's annual business conclave with strong NCR corporate participation.",
    domain: "Strategy",
    format: "Online Prelims → MDI Campus Finals",
    registrationDeadline: new Date("2026-08-08"),
    preliminaryDate: new Date("2026-09-01"),
    eventDate: new Date("2026-09-19"),
    location: "Gurgaon",
    mode: "HYBRID",
    teamSizeMin: 2,
    teamSizeMax: 4,
    prizePool: "₹1.5 Lakhs",
    registrationUrl:
      "https://unstop.com/competitions/imperium-24-mdi-gurgaon-120578",
    eligibility: "MBA/PGDM students across India",
    status: "REGISTRATION_OPEN",
    isFeatured: false,
    tags: ["Delhi-NCR", "B-school-fest", "national"],
    hostCollege: "MDI Gurgaon",
  },
  {
    slug: "iift-quo-vadis-2026",
    title: "IIFT Quo Vadis — Case Challenge",
    organizer: "IIFT Delhi",
    description:
      "Case challenge at Quo Vadis, the international business summit of Indian Institute of Foreign Trade, Delhi campus.",
    domain: "Strategy",
    format: "Online Prelims → IIFT Delhi Finale",
    registrationDeadline: new Date("2026-07-18"),
    preliminaryDate: new Date("2026-08-12"),
    eventDate: new Date("2026-09-05"),
    location: "New Delhi",
    mode: "HYBRID",
    teamSizeMin: 2,
    teamSizeMax: 4,
    prizePool: "₹1 Lakh",
    registrationUrl:
      "https://unstop.com/competitions/quo-vadis-international-business-summit-iift-delhi-1271",
    eligibility: "MBA/PGDM students; strong Delhi-NCR participation",
    status: "REGISTRATION_OPEN",
    isFeatured: false,
    tags: ["Delhi-NCR", "B-school-fest", "trade"],
    hostCollege: "IIFT Delhi",
  },
  {
    slug: "colgate-transcend-2026",
    title: "Colgate Transcend",
    organizer: "Colgate-Palmolive India",
    description:
      "Brand and marketing strategy competition focused on oral care and personal care categories in India.",
    domain: "Marketing",
    format: "Online → Campus Finale",
    registrationDeadline: new Date("2026-09-15"),
    preliminaryDate: new Date("2026-10-08"),
    eventDate: new Date("2026-11-15"),
    location: "Mumbai",
    mode: "HYBRID",
    teamSizeMin: 2,
    teamSizeMax: 3,
    prizePool: "₹3 Lakhs",
    registrationUrl:
      "https://unstop.com/competitions/colgate-transcend-colgate-palmolive-india-limited-488",
    eligibility: "MBA students nationwide",
    status: "UPCOMING",
    isFeatured: false,
    tags: ["FMCG", "marketing", "branding"],
    hostCollege: null,
  },
  {
    slug: "pg-ceo-challenge-2026",
    title: "P&G CEO Challenge",
    organizer: "Procter & Gamble",
    description:
      "P&G's flagship B-school challenge focused on brand building, consumer insight, and general management decision-making.",
    domain: "Marketing",
    format: "Online Qualifier → P&G Office Finale",
    registrationDeadline: new Date("2026-08-18"),
    preliminaryDate: new Date("2026-09-15"),
    eventDate: new Date("2026-10-04"),
    location: "Mumbai",
    mode: "HYBRID",
    teamSizeMin: 2,
    teamSizeMax: 4,
    prizePool: "₹4 Lakhs + P&G PPIs",
    registrationUrl:
      "https://unstop.com/competitions/pg-ceo-challenge-procter-and-gamble-337",
    eligibility: "MBA students nationwide",
    status: "UPCOMING",
    isFeatured: false,
    tags: ["FMCG", "marketing", "corporate"],
    hostCollege: null,
  },
  {
    slug: "reckitt-kickstart-2026",
    title: "Reckitt Kickstart",
    organizer: "Reckitt",
    description:
      "Marketing and brand strategy competition for health, hygiene, and home care brands including Dettol and Harpic.",
    domain: "Marketing",
    format: "Online Qualifier → Virtual Finals",
    registrationDeadline: new Date("2026-07-30"),
    preliminaryDate: new Date("2026-08-22"),
    eventDate: new Date("2026-09-14"),
    location: "Gurgaon (Finale)",
    mode: "HYBRID",
    teamSizeMin: 2,
    teamSizeMax: 3,
    prizePool: "₹4 Lakhs + Reckitt PPIs",
    registrationUrl:
      "https://unstop.com/competitions/reckitt-kickstart-reckitt-1298",
    eligibility: "MBA marketing students preferred, all welcome",
    status: "REGISTRATION_OPEN",
    isFeatured: false,
    tags: ["FMCG", "marketing", "corporate"],
    hostCollege: null,
  },
  {
    slug: "nivea-marathon-2026",
    title: "NIVEA Marathon",
    organizer: "Beiersdorf (NIVEA)",
    description:
      "Skincare and personal care marketing competition developing go-to-market strategies for NIVEA product lines in India.",
    domain: "Marketing",
    format: "Virtual Case → Finale",
    registrationDeadline: new Date("2026-05-15"),
    eventDate: new Date("2026-06-14"),
    location: "Mumbai",
    mode: "HYBRID",
    teamSizeMin: 2,
    teamSizeMax: 3,
    prizePool: "₹2 Lakhs",
    registrationUrl:
      "https://unstop.com/competitions/nivea-marathon-beiersdorf-india-private-limited-406",
    eligibility: "MBA students",
    status: "COMPLETED",
    isFeatured: false,
    tags: ["FMCG", "marketing", "skincare"],
    hostCollege: null,
  },
] as const;