export type CompetitionSource = {
  slug: string;
  unstopId: number;
  organizer: string;
  domain: "Strategy" | "Marketing" | "Operations" | "Finance" | "Analytics";
  format: string;
  location: string;
  mode?: "ONLINE" | "OFFLINE" | "HYBRID";
  teamSizeMin?: number;
  teamSizeMax?: number;
  eligibility?: string;
  isFeatured?: boolean;
  tags: string[];
  hostCollege?: string | null;
  /** Override when Unstop only exposes registration window */
  eventDate?: string;
  preliminaryDate?: string;
};

/** Curated Unstop listings — dates are fetched live from the API at seed/sync time. */
export const competitionSources: CompetitionSource[] = [
  {
    slug: "asian-paints-canvas-2026",
    unstopId: 1690371,
    organizer: "Asian Paints",
    domain: "Marketing",
    format: "Campus Round → Zonal → National Finale",
    location: "Mumbai",
    mode: "HYBRID",
    isFeatured: true,
    tags: ["corporate", "marketing", "FMCG", "flagship", "heritage"],
  },
  {
    slug: "coca-cola-mantra-2026",
    unstopId: 1684185,
    organizer: "Coca-Cola India",
    domain: "Marketing",
    format: "Online Case → National Finale",
    location: "Online",
    mode: "ONLINE",
    teamSizeMin: 2,
    teamSizeMax: 4,
    eligibility: "MBA students across India",
    isFeatured: true,
    tags: ["corporate", "marketing", "FMCG", "flagship", "pre-placement"],
  },
  {
    slug: "marico-level-up-2026",
    unstopId: 1697666,
    organizer: "Marico",
    domain: "Marketing",
    format: "Online Challenge → Finale",
    location: "Mumbai",
    mode: "HYBRID",
    isFeatured: true,
    tags: ["FMCG", "marketing", "corporate"],
  },
  {
    slug: "amex-campus-challenge-strategy-2026",
    unstopId: 1688123,
    organizer: "American Express",
    domain: "Strategy",
    format: "Strategy Track → National Finals",
    location: "Online",
    mode: "ONLINE",
    isFeatured: true,
    tags: ["corporate", "strategy", "finance"],
  },
  {
    slug: "amex-campus-challenge-product-2026",
    unstopId: 1698314,
    organizer: "American Express",
    domain: "Strategy",
    format: "Product Track → National Finals",
    location: "Online",
    mode: "ONLINE",
    tags: ["corporate", "strategy", "product"],
  },
  {
    slug: "shri-ram-consulting-olympiad-2026",
    unstopId: 1687354,
    organizer: "180 Degrees Consulting SRCC",
    domain: "Strategy",
    format: "Online Quiz → Case Rounds → Finals",
    location: "New Delhi",
    mode: "ONLINE",
    teamSizeMin: 1,
    teamSizeMax: 3,
    eligibility: "Open to students across India",
    isFeatured: true,
    tags: ["consulting", "B-school-fest", "Delhi-NCR"],
    hostCollege: "SRCC Delhi",
    eventDate: "2026-07-26",
  },
  {
    slug: "the-consultants-2026",
    unstopId: 1681777,
    organizer: "ThriveMBA",
    domain: "Strategy",
    format: "Online Case Rounds → Finals",
    location: "Online",
    mode: "ONLINE",
    teamSizeMin: 1,
    teamSizeMax: 3,
    eligibility: "MBA students and aspirants across India",
    tags: ["consulting", "case-competition", "B-school"],
  },
  {
    slug: "marketer-of-the-year-2026",
    unstopId: 1683862,
    organizer: "ThriveMBA",
    domain: "Marketing",
    format: "Marketing Case Rounds → Finals",
    location: "Online",
    mode: "ONLINE",
    teamSizeMin: 1,
    teamSizeMax: 2,
    eligibility: "MBA students and aspirants across India",
    tags: ["marketing", "case-competition", "B-school"],
  },
  {
    slug: "prodman-of-the-year-2026",
    unstopId: 1687285,
    organizer: "ThriveMBA",
    domain: "Operations",
    format: "Product Management Challenge → Finals",
    location: "Online",
    mode: "ONLINE",
    teamSizeMin: 1,
    teamSizeMax: 2,
    eligibility: "MBA students and aspirants across India",
    tags: ["product", "case-competition", "B-school"],
  },
  {
    slug: "global-quant-finance-challenge-2026",
    unstopId: 1687324,
    organizer: "Nexus Club, SRM IST",
    domain: "Finance",
    format: "Online Finance Challenge → Finals",
    location: "Online",
    mode: "ONLINE",
    teamSizeMin: 1,
    teamSizeMax: 4,
    tags: ["finance", "investment-banking", "quant"],
  },
  {
    slug: "business-leadership-simulator-2026",
    unstopId: 1693713,
    organizer: "YAI Infraventure",
    domain: "Strategy",
    format: "Business Simulation → Leadership Rounds",
    location: "Online",
    mode: "ONLINE",
    tags: ["simulation", "entrepreneurship", "strategy"],
  },
  {
    slug: "conquest-26",
    unstopId: 1664678,
    organizer: "Entrepreneurship Cell, BITS Pilani",
    domain: "Strategy",
    format: "Startup Accelerator → Demo Day",
    location: "Online",
    mode: "ONLINE",
    teamSizeMin: 2,
    teamSizeMax: 6,
    eligibility: "Early-stage startup founders",
    tags: ["startup", "accelerator", "innovation"],
    hostCollege: "BITS Pilani",
    eventDate: "2026-07-20",
  },
  {
    slug: "nextgen-marketing-challenge-2026",
    unstopId: 1694692,
    organizer: "Finance Veda",
    domain: "Marketing",
    format: "Brand Strategy → Digital Marketing Rounds",
    location: "Online",
    mode: "ONLINE",
    teamSizeMin: 2,
    teamSizeMax: 4,
    eligibility: "MBA / PGDM students across India",
    tags: ["marketing", "B-school", "brand-strategy"],
  },
  {
    slug: "sundaram-pitch-fest-tech-2026",
    unstopId: 1684385,
    organizer: "E-Cell IIT Kharagpur & Sundaram Finance",
    domain: "Strategy",
    format: "Pitch Submission → Finale",
    location: "Online",
    mode: "ONLINE",
    teamSizeMin: 2,
    teamSizeMax: 5,
    tags: ["pitch", "technology", "IIT"],
    hostCollege: "IIT Kharagpur",
    eventDate: "2026-06-28",
  },
  {
    slug: "interactup-case-competition-2026",
    unstopId: 1678429,
    organizer: "InteractUp",
    domain: "Strategy",
    format: "Online Case Challenge",
    location: "Online",
    mode: "ONLINE",
    teamSizeMin: 1,
    teamSizeMax: 4,
    tags: ["case-competition", "networking", "B-school"],
  },
  {
    slug: "hackon-amazon-6-2026",
    unstopId: 1682652,
    organizer: "Amazon India",
    domain: "Analytics",
    format: "Online Hackathon → Finals",
    location: "Online",
    mode: "ONLINE",
    teamSizeMin: 2,
    teamSizeMax: 4,
    tags: ["corporate", "technology", "hackathon"],
  },
  {
    slug: "et-ai-hackathon-2-2026",
    unstopId: 1675680,
    organizer: "The Economic Times",
    domain: "Analytics",
    format: "AI Innovation Challenge → Finals",
    location: "Online",
    mode: "ONLINE",
    teamSizeMin: 1,
    teamSizeMax: 4,
    tags: ["AI", "hackathon", "innovation"],
  },
];